-- Mokaru Guam — the Oct 1 pivot: one booking table, two kinds of request
-- Design: MokaruGuam/pivot-oct1-design.md §5 (v2, 2026-09-11)
--
-- WHAT CHANGES
-- The guided charter ends 2026-09-30. From 10/1 the same pipeline carries two
-- kinds of request instead of one:
--   tour       — we arrange a partner's activity. The guest pays us nothing;
--                the partner pays a 20% commission. No PayPal on this path.
--   restaurant — we book a table. $10, authorised at request time, captured
--                only when the table is actually held, voided otherwise.
--
-- 🔴 RUN THIS ONCE IN SUPABASE → SQL EDITOR, BEFORE THE CODE IS DEPLOYED.
-- addBooking() in src/lib/store.ts inserts an EXPLICIT column list. Shipping
-- the code against a table without these columns makes every booking fail — on
-- the one site that takes money. This is the order established on 2026-09-03
-- when the `hotel` column was added:
--   1. owner runs this SQL
--   2. the columns are verified to exist (see the check at the bottom)
--   3. only then is the code deployed
--
-- 🔴 BEFORE RUNNING: confirm the project ref is zqzbilvintyzgkliovvn and that
-- the SQL editor is pointed at Mokaru. This Supabase project is SHARED WITH
-- DaDeal. Look at the ref in the URL; do not trust the browser tab.
--
-- Safe against the code running right now: every column added here is nullable
-- (or defaulted), and the current insert does not mention any of them.

-- ---------------------------------------------------------------------------
-- 1. Which kind of request this is
-- ---------------------------------------------------------------------------
-- NULL on every existing row, on purpose. Those are charter bookings taken
-- before the question existed, and the code reads `request_type ?? "tour"` so
-- their cancellation and refund behaviour does not change by one cent. Same
-- principle as the `hotel` column: "we never asked" must stay distinguishable
-- from "they answered".
alter table public.bookings
  add column if not exists request_type text;

-- The partner company (tour) or the restaurant (first choice). One column
-- rather than two, because a row is only ever one kind of request.
alter table public.bookings
  add column if not exists partner_name text;

-- ---------------------------------------------------------------------------
-- 2. Restaurant-only fields
-- ---------------------------------------------------------------------------
-- What to do when the first-choice restaurant is full. Asked on the form and
-- REQUIRED there, because the alternative is emailing the guest mid-arrangement
-- and waiting — which is exactly the delay that outlives a PayPal hold.
--   cancel  — stop here, charge nothing
--   suggest — propose somewhere else (one proposal, per the terms)
alter table public.bookings
  add column if not exists fallback_choice text;

-- Optional hints used only to make that one proposal a good one.
alter table public.bookings
  add column if not exists budget_hint text;

alter table public.bookings
  add column if not exists cuisine_hint text;

-- ---------------------------------------------------------------------------
-- 3. Reference number
-- ---------------------------------------------------------------------------
-- Printed in the subject line of every email we send a partner or a restaurant
-- ("[Mokaru] 予約依頼 / Joe's Jet Ski / 2026-10-15 / 山田 / #0012"), so that at
-- month end the partner can search their own inbox for [Mokaru] and we can
-- point at one booking at a time when reconciling the 20%.
--
-- Numbered by the DATABASE, not the application. Counting rows in application
-- code to derive "the next number" gives two simultaneous requests the same
-- one, and a duplicated reference number is worse than no reference number:
-- it silently merges two bookings during reconciliation.
--
-- `by default` rather than `always` so a value can still be written explicitly
-- if a row ever has to be restored by hand.
alter table public.bookings
  add column if not exists ref_no integer generated by default as identity;

-- ---------------------------------------------------------------------------
-- 4. Constraints
-- ---------------------------------------------------------------------------
-- Postgres has no "add constraint if not exists", so each one is guarded to
-- keep this file safe to re-run.
--
-- NOTE ON WHAT IS *NOT* HERE: the design doc said a CHECK on plan_id would
-- have to be rebuilt to let restaurant rows through. Reading the live schema
-- (supabase/schema.sql) shows there is no CHECK on plan_id — only on `status`
-- and `payment`, neither of which the pivot changes. Nothing to rebuild.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'bookings_request_type_check'
  ) then
    alter table public.bookings
      add constraint bookings_request_type_check
      check (request_type is null or request_type in ('tour', 'restaurant'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'bookings_fallback_choice_check'
  ) then
    alter table public.bookings
      add constraint bookings_fallback_choice_check
      check (fallback_choice is null or fallback_choice in ('cancel', 'suggest'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'bookings_ref_no_key'
  ) then
    alter table public.bookings
      add constraint bookings_ref_no_key unique (ref_no);
  end if;
end $$;

-- Both constraints accept NULL deliberately: existing rows have none of these
-- values, and a migration that rejected them would fail on the spot.

comment on column public.bookings.request_type is
  'tour = we arrange a partner activity (guest pays us nothing). restaurant = we book a table ($10). NULL = charter booking taken before 2026-10-01; code reads it as ''tour''.';

comment on column public.bookings.partner_name is
  'Partner company (tour) or restaurant, first choice (restaurant).';

comment on column public.bookings.fallback_choice is
  'Restaurant only. What the guest chose for a full restaurant: cancel = charge nothing, suggest = propose an alternative (one proposal).';

comment on column public.bookings.ref_no is
  'Reference number shown to partners and restaurants (#0012). Assigned by the database so concurrent requests cannot collide.';

-- ---------------------------------------------------------------------------
-- 5. 🔴 VERIFY BEFORE DEPLOYING THE CODE
-- ---------------------------------------------------------------------------
-- Run this and read the result. Six rows must come back. A missing column is
-- not a warning at deploy time — it is every booking failing.
--
--   select column_name, data_type, is_nullable
--     from information_schema.columns
--    where table_schema = 'public'
--      and table_name = 'bookings'
--      and column_name in ('request_type','partner_name','fallback_choice',
--                          'budget_hint','cuisine_hint','ref_no')
--    order by column_name;
--
-- And confirm existing rows were numbered and left otherwise untouched:
--
--   select ref_no, name, preferred_date, request_type, status, payment
--     from public.bookings order by ref_no;
--
-- request_type must be NULL on every pre-existing row. If any of them came
-- back as 'tour', something backfilled them — stop and say so, because the
-- refund branch keys off exactly that distinction.
